export const LEAGUE_LIST_REQUEST = 'LEAGUE_LIST_REQUEST';
export const LEAGUE_LIST_SUCCESS = 'LEAGUE_LIST_SUCCESS';
export const LEAGUE_LIST_FAIL = 'LEAGUE_LIST_FAIL';

export const LEAGUE_DETAILS_REQUEST = 'LEAGUE_DETAILS_REQUEST';
export const LEAGUE_DETAILS_SUCCESS = 'LEAGUE_DETAILS_SUCCESS';
export const LEAGUE_DETAILS_FAIL = 'LEAGUE_DETAILS_LEAGUE';

export const LEAGUE_CREATE_REQUEST = 'LEAGUE_CREATE_REQUEST';
export const LEAGUE_CREATE_SUCCESS = 'LEAGUE_CREATE_SUCCESS';
export const LEAGUE_CREATE_FAIL = 'LEAGUE_CREATE_FAIL';
export const LEAGUE_CREATE_RESET = 'LEAGUE_CREATE_RESET';
